### ISSUE TITLE
Finish Base Styles

### ISSUE THREAD

**Issue by joshuafbarker** [joshuafbarker/hazel#2]
### Description
Finish all the base styles for the project.

### Tasks
- [ ] Finish `body` and `html` styles.
- [ ] Default fonts and colors
- [ ] Begin adding additional font and color classes
- [ ] Add all properties for legibility and accessibility
- [ ] Add any resets necessary
